services:
  # MongoDB - usando tu imagen existente
  mongodb:
    image: mongo:7.0-jammy
    container_name: eventos_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_URI: mongodb://admin:password123@mongodb:27017/eventos_db
      MONGO_DB_NAME: eventos_db
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      RUST_LOG: info
      LlaveJWT: DKJDHFDasdss1238/95222sdsdsd-*885sd9**
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: notifications_queue
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: eventos_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # Puerto AMQP
      - "15672:15672"   # Puerto management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  # Tu aplicación Rust
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sebastiandll/rust_eventos_app:v10.0
    container_name: rust_eventos_app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: mongodb://mongodb:27017/eventos_db
      MONGO_DB_NAME: eventos_db
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      RUST_LOG: info
      LlaveJWT: DKJDHFDasdss1238/95222sdsdsd-*885sd9**
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: notifications_queue
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge