services:
  db:
    image: postgres:15-alpine
    container_name: bd_usuarios
    environment:
      POSTGRES_DB: db_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lilianjc123
    ports:
      - "5433:5432"  # Puerto externo 5433, interno 5432 (estándar de PostgreSQL)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: auth_service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=db_usuarios
      - DB_PASSWORD=lilianjc123
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge