services:
  db:
    image: postgres:15-alpine
    container_name: bd_usuarios
    environment:
      POSTGRES_DB: db_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lilianjc123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network
    restart: unless-stopped

  app:
    build: .
    container_name: auth_service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - auth_network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge